### ISSUE TITLE
Edges are in the center instead of the side + Jumping into a node changes the edges to its children

### ISSUE THREAD

**Issue by sifran-github** [freeplane/freeplane#1090] opened 2023-04-11 22:29 UTC
**Describe the bug**
(see title)

**To Reproduce**
1. open the map
2. jump into nodes "ITEM 2" or "ITEM 3", for example.
3. you can see the issue.

**Expected behavior**

- The edge should stay in the position that it was before jumping in. it shouldn't "jump" to the center of the node.
- I guess it should "remember" the location of the edge from the parent structure outside the jump, even if we cant see the outside structure. This is justifiable, since other features are being "remembered": for example, if the node layout is set to "auto", it will still reflect its parent, even if we jump into it.

**Mind map files**
https://github.com/freeplane/freeplane/files/10677064/test_new_version_v2.zip

**Screenshots**
![image](https://user-images.githubusercontent.com/5730355/231301184-ddfbc479-b8af-4611-847e-185285a3f8fe.png)

**Version**
freeplane-1.11.1-pre29

**Additional context**
I did remember that I wrote about a similar issue... and after searching, I found: https://github.com/freeplane/freeplane/discussions/960#discussioncomment-4893676, but it is NOT the same issue.

**Comment by sifran-github** [comment] 2023-04-12 00:16
Actually, Its not only related to jumping in.

For example, here I set the root layout to this style (real root, no jump in):
![image](https://user-images.githubusercontent.com/5730355/231314162-27759bf9-cd79-418f-ad5a-5e8768a174cf.png)
I expect it to behave like an outline, but the edge is in the center.

For example, if I change the map view to outline view (view->view settings->outline view), it looks better:
![image](https://user-images.githubusercontent.com/5730355/231314330-88c9743b-e058-482d-932f-5474e1caca72.png)

Regarding the solution: I understand that sometimes the user will might the edge to be in the center. Maybe its related to the chosen layout, or maybe the way edges are behaving should also be some property that should be defined? I'm not really sure.

Map: [outline_test.zip](https://github.com/freeplane/freeplane/files/11205881/outline_test.zip)

**Comment by dpolivaev** [comment] 2023-04-14 15:18
The outline view layout looks more compact than the map layout, but it is not a bug.

I can not reproduce pictures from https://github.com/freeplane/freeplane/issues/1090#issue-1663307206 with edges running through the nodes.

Generally, if node becomes a root after jump in AND child side was chosen to be the right or the left automatically, Freeplane allows to place the nodes on the both sides. Therefore in a specific case of a vertical layout when child nodes are placed below or above the parent like in you example, their position changes so that the both sides can be used until you jump out.

It should allow the user to use the both sides for placement after jump-in.

Because I do not use it myself I do not have an expertise to decide if this behavior should be changed and in which cases it should be changed.

**Comment by sifran-github** [comment] 2023-04-14 21:45
> The outline view layout looks more compact than the map layout, but it is not a bug.

Its not about how "compact" it is, it is about the edge (line) in the center. you cant see the difference, that one has a line in the center and the other dont?
 
> I can not reproduce pictures from [#1090 (comment)](https://github.com/freeplane/freeplane/issues/1090#issue-1663307206) with edges running through the nodes.

Open the map and jump into these nodes.
Or just create root node like at https://github.com/freeplane/freeplane/issues/1090#issuecomment-1504316243 to see the line in the center.

it is a bug.

**Comment by sifran-github** [comment] 2023-04-14 22:12
I color the nodes edges so it can be clearer.

Jump in:
![image](https://user-images.githubusercontent.com/5730355/232163315-34b209c7-2984-4ca7-aa43-a2407931874a.png)

Regular root node:
![image](https://user-images.githubusercontent.com/5730355/232163425-f4354777-2b60-4417-bc2e-5eb38bce2948.png)

**Comment by sifran-github** [comment] 2023-04-30 18:43
this bug stil exists in freeplane-1.11.1-pre31

**Comment by dpolivaev** [comment] 2023-05-01 10:22
Fixed in Preview 1.11.1-pre32

**Closed as completed by dpolivaev** 2023-05-01 10:22 UTC
Labels: bug

**Comment by dpolivaev** [comment] 2023-05-01 10:28
I have finally reproduced and fixed the issue which was also depending on user settings. Therefore I could not observe it on my installation until I changed my settings.

**Comment by sifran-github** [comment] 2023-05-01 15:20
confirming that it is fixed in Preview 1.11.1-pre32, for root items and also when jumping in.
