### ISSUE TITLE
The undo action using Ctrl+Z does not work as expected after creating a new node

### ISSUE THREAD

**Issue by fossbrandon** [freeplane/freeplane#1010] opened 2023-02-16 00:18 UTC
**Describe the bug**
When I add a new node and then use the key combination of `Ctrl+Z` to try and undo the node creation, it opens the text prompt instead. 

**To Reproduce**
1. Add a new node
2. Press `Ctrl+Z` to try and undo the creation
4. See the unexpected text prompt rather than the removal of the node

**Expected behavior**
I would expect the node to be removed rather than presented with a text prompt.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Additional context**
If I add a node and then use the `Undo` back arrow button, it removes the node as expected. Also, if I click away from the new node and then use the key combination, it also removes the node as expected.

**Comment by bepolymathe** [comment] 2023-02-18 14:49
I'm not sure if this is a bug because if I do Ctrl+z once I can re-edit the node (which is the step before) and if I type Ctrl+z a second time it deletes the node (which is the step before again).

**Comment by fossbrandon** [comment] 2023-02-20 17:34
I didn't think of that, so I tried doing the undo twice using Ctrl+Z and it still just leaves me in the edit text mode. 
![image](https://user-images.githubusercontent.com/46940941/220170629-be909364-0fe1-4112-a30b-279aaf4e4694.png)

It doesn't let me undo the node creation until I click away again and then use Ctrl+Z.

**Comment by bepolymathe** [comment] 2023-02-21 09:36
> I didn't think of that, so I tried doing the undo twice using Ctrl+Z and it still just leaves me in the edit text mode.

Sorry but i can’t reproduce this on linux 🤔 

What’s your option for "keyboard entry outside a node" (in "behaviour" tab) ?

**Comment by fossbrandon** [comment] 2023-02-21 10:53
Must be a Windows issue or user error then 😮‍💨 And I'm sorry but I can't find that option in my preferences.

**Comment by peppbaggio** [comment] 2023-06-15 02:32
Hello, I can confirm this bug for Manjaro Linux at least. 
OS version: Manjaro Linux 23.0.0
Freeplane ver. 1.11.2
I use Ctrl+Z twice, and more, and more. And the node is still in the edit mode. 
Really uncomfortable.

**Comment by HaaiHenkie** [comment] 2023-06-15 05:31
I think what you describe is as designed and it makes sense to me as is. When you create a new node, you end up in edit mode, like you describe. So it is logical to me that undo relates to what you are writing in edit mode. You want to be able to undo mistakes while writing the text in the node, right? Since you haven't written anything, undo will have no effect. If you go out of edit mode, normally by pressing enter, you end up with an empty node. If you use undo now, it is in the context of the mind map and it will remove the node you have just created like you expected in the first place.

**Comment by macmarrum** [comment] 2023-06-15 06:33
I can confirm on Arch Linux the same behavior. Despite `Preferences…->Behaviour->In-line node editor->Display inline editor for all new nodes` being off, `Ctrl+Z` goes into "in-line edit" instead of undoing node creation.

Until `Ctrl+Z` works as expected, here's a workaround.
If you don't want an inline editor for all new nodes, you can use the script [insertChildForSelected.groovy](https://raw.githubusercontent.com/macmarrum/freeplane-scripting/main/src/scripts/insertChildForSelected.groovy), e.g. assign it the hot key `Insert` or `Tab` or whatever you have configured to insert a node.
If `Preferences…->Behaviour->On key type` is set to `Overwrite content`, then also the flow of adding new text content will be retained – hit `Insert`, type your content.
Using the script has the additional benefit of being able to add a new child for every selected node.

**Comment by HaaiHenkie** [comment] 2023-06-15 12:31
I think the problem is as follows: after creating the new node it is opened in edit mode, but visually it looks like you created an empty node since there is no text editing cursor. Pressing Ctrl+Z only visualizes that you are in edit mode. It looks like you are going into edit mode, but you actually already were editing the node. If you press subsequently Tab, Enter and Ctrl+Z, the undo actually works as expected. The Enter takes you out of editing mode. Alternatively, pressing Tab and then Esc is also a way of undoing creating the node.

**Comment by peppbaggio** [comment] 2023-06-16 01:02
Thanks a lot, HaaiHenkie, I'll try. But it is a really strange behaviour for me. To my mind, Ctrl+Z should be Ctrl+Z always and anywhere, and it should cancel the last action...

**Comment by HaaiHenkie** [comment] 2023-06-16 05:58
Suppose you create a new node, type the node text and make a typo. Now you want to use Ctrl+Z to undo your typing. It would be equally strange if Ctrl+Z would undo creating the node in this situation, right? That is why while in text editing mode Ctrl+Z will always relate to the text you are typing and not to changes at mind map level. I can understand this is strange if you created a node and did not write any text yet. But you are in fact editing the node text. Changing the behaviour of Ctrl+Z here to undo things at mind map level would lead to unexpected behaviour in other situations, like described above. I believe any mind map program is doing this in the same way. I think the only thing that can be improved here, is giving you as a user proper visual feedback that you are editing the new node's text.

**Comment by dpolivaev** [comment] 2023-06-16 06:02
I agree that I can improve the logic.

**Comment by dpolivaev** [comment] 2023-06-17 20:03
Preview 1.11.5_10

**Closed as completed by dpolivaev** 2023-06-17 20:03 UTC
Labels: bug
