### ISSUE TITLE
Overlap occurs

### ISSUE THREAD

**Issue by zdahai** [freeplane/freeplane#1643] opened 2024-01-16 14:57 UTC
Dear developer, hello
I am a user from China and recently encountered the following error while using this software. I have uploaded a screenshot.
This error seems to be caused by the software being turned on for a long time, and after restarting the software for a period of time, this error occurs due to discounts

**Desktop (please complete the following information):**
 - OS: Windows11
 - Version：1.11.8
 - Java Version：15.0.10

![2024-01-16_224156](https://github.com/freeplane/freeplane/assets/93262405/c3f81a57-8dce-485b-9267-ff32ee549b3c)

**Comment by dpolivaev** [comment] 2024-01-16 15:02
Duplicate of https://github.com/freeplane/freeplane/issues/1348

**Closed as completed by dpolivaev** 2024-01-16 15:02 UTC
Labels: bug, duplicate, not reproducible, can't do, not our bug
