### ISSUE TITLE
Freeplance 1.12.6 crashes on startup Fedora 41 OpenJDK 21

### ISSUE THREAD

**Issue by chriscz** [freeplane/freeplane#2108] opened 2024-11-13 01:57 UTC
**Describe the bug**
The application crashes as soon as you try to open it.

I have tried disabling the code explorer plugin, but get the same error.

Even removing all the plugins still raises the exception.

**To Reproduce**
1. Install freeplane from the bin zipfile
2. Run `freeplane` in the terminal

**Expected behavior**
The application must start successfully

**Desktop**
-
 - OS: Fedora 
 - Version: 41
 - Java Version:
   ```
   openjdk 21.0.5 2024-10-15
   OpenJDK Runtime Environment (Red_Hat-21.0.5.0.11-1) (build 21.0.5+11)
   OpenJDK 64-Bit Server VM (Red_Hat-21.0.5.0.11-1) (build 21.0.5+11, mixed mode, sharing)
   ```

**Additional context**
Full traceback
```
WARNING: package sun.swing.shell not in java.desktop
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.freeplane.launcher.Launcher (file:/home/chris/.local/opt/freeplane/freeplanelauncher.jar)
WARNING: Please consider reporting this to the maintainers of org.freeplane.launcher.Launcher
WARNING: System::setSecurityManager will be removed in a future release
Knopflerfish OSGi framework launcher, version <unknown>
Copyright 2003-2020 Knopflerfish. All Rights Reserved.
See http://www.knopflerfish.org for more information.

Created Framework: org.knopflerfish.framework, version=8.0.11.
Background mode.
Nov 13, 2024 11:54:50 AM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://1:1/freeplane.properties
Nov 13, 2024 11:54:50 AM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://1:2/org/freeplane/main/application/
Installed: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.bugreport (id#2)
Installed: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.codeexplorer (id#3)
Installed: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.formula (id#4)
Installed: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.jsyntaxpane (id#5)
Installed: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.latex (id#6)
Installed: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.markdown (id#7)
Installed: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.openmaps (id#8)
Installed: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.script (id#9)
Installed: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.svg (id#10)
Started: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.bugreport (id#2)
Started: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.codeexplorer (id#3)
Started: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.formula (id#4)
Started: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.jsyntaxpane (id#5)
Started: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.latex (id#6)
Started: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.markdown (id#7)
Started: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.openmaps (id#8)
Started: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.script (id#9)
Started: reference:file:/home/chris/.local/opt/freeplane/plugins/org.freeplane.plugin.svg (id#10)
Nov 13, 2024 11:54:50 AM org.freeplane.core.util.LogUtils info
INFO: language resources for en found
Nov 13, 2024 11:54:50 AM org.freeplane.core.util.LogUtils info
INFO: freeplane_version = 1.12.6; freeplane_xml_version = freeplane 1.12.1
git revision = 6c38f557492aa51dd5c79fa4793a7a222e8d1d03 dpolivaev 2024-09-16T12:00:35Z
java_version = 21.0.5; os_name = Linux; os_version = 6.11.6-300.fc41.x86_64
Nov 13, 2024 11:54:50 AM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date format d/M/yy
Nov 13, 2024 11:54:50 AM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date time format d/M/yy, h:mm a
Installing shutdown hook.
Framework launched
Nov 13, 2024 11:54:51 AM org.freeplane.core.util.LogUtils warn
WARNING: Exception in org.freeplane.core.ui.components.OneTouchCollapseResizer.setExpanded(enabled): java.lang.RuntimeException: Method not implemented
Nov 13, 2024 11:54:51 AM org.freeplane.core.util.LogUtils severe
SEVERE: Exception in thread "pool-1-thread-1"
java.lang.RuntimeException: Method not implemented
        at org.freeplane.main.headlessmode.HeadlessMapViewController.getMapViewComponent(HeadlessMapViewController.java:185)
        at org.freeplane.plugin.codeexplorer.map.ShowDependingNodesAction.<init>(ShowDependingNodesAction.java:57)
        at org.freeplane.plugin.codeexplorer.map.CodeMapController.<init>(CodeMapController.java:66)
        at org.freeplane.plugin.codeexplorer.CodeModeControllerFactory.createModeController(CodeModeControllerFactory.java:72)
        at org.freeplane.plugin.codeexplorer.Activator$1.installExtension(Activator.java:49)
        at org.freeplane.main.osgi.ActivatorImpl$OsgiExtentionInstaller.installExtensions(ActivatorImpl.java:271)
        at org.freeplane.main.osgi.ActivatorImpl.installControllerExtensions(ActivatorImpl.java:307)
        at org.freeplane.main.osgi.ActivatorImpl.access$100(ActivatorImpl.java:66)
        at org.freeplane.main.osgi.ActivatorImpl$2.run(ActivatorImpl.java:230)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by dpolivaev** [comment] 2024-11-13 12:41
Lines
java.lang.RuntimeException: Method not implemented
at org.freeplane.main.headlessmode.HeadlessMapViewController.getMapViewComponent(HeadlessMapViewController.java:185)

indicate that you try to use Java version not including UI (headless)

Duplicate of https://github.com/freeplane/freeplane/issues/2101

**Closed as completed by dpolivaev** 2024-11-13 12:41 UTC
Labels: duplicate, not a bug

**Comment by kevinpinscoe** [comment] 2025-05-03 01:33
I got around this by installing sudo dnf install java-21-openjdk-devel
 on Fedora 42. I think the deualt java installed by Fedora is headless. Don't forget to use command sudo alternatives --config java and pick the java version you just installed.
