### ISSUE TITLE
Drag and drop as a child node is not possible anymore

### ISSUE THREAD

**Issue by Bommi46** [freeplane/freeplane#949] opened 2023-01-16 06:45 UTC
**Describe the bug**
when you drag a node by mouse you can drop it as a sibling or as a child
in the latest version: drop as a child is not possible anymore. drop as a sibling still works
workaround: I cut the node and paste it as a child.

**To Reproduce**
1. klick a node
2. drag it to a different node
3. move it to the upper edge: you see a grey shade. you can drop the node. it becomes a sibling node.
4. move it to the right edge: you should see a grey shade. but you don't. if you drop the node nevertheless: nothing happens.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - cc7da98e621bc5c9fb7a86ce80cd56f37aa5aa93 Dimitry Polivaev 2023-01-13T21:41:31Z
Java-Version: 15.0.7

**Comment by dpolivaev** [comment] 2023-01-16 06:50
Already fixed, check out the latest preview

**Comment by Bommi46** [comment] 2023-01-16 08:08
thank you!

**Comment by ldmpub** [comment] 2023-01-16 13:22
Duplicate of / same bug reported here: https://github.com/freeplane/freeplane/issues/940

**Closed as completed** 2023-01-20 16:14 UTC
Labels: bug, duplicate
