### ISSUE TITLE
Displayed font does not match setting in styles

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1294] opened 2023-07-05 13:52 UTC
**Describe the bug**
In a new map, editing node note defaults to SansSerif 12pt.  But the style is set at Segoe UI Semilight 10pt.

**To Reproduce**
1. open new map
2. create child node
3. open node note
4. font & size are different than those in Note style

**Expected behavior**
Expected the note editor to use the settings in Note style.

**Mind map files**
attached

**Screenshots**
attached

**Desktop (please complete the following information):**
- OS: windows 11 home
- Version: 22H2
- Java Version: 17 0 7
- Freeplane: Freeplane-Setup-1.11.5-pre16

**Additional context**
I cannot pinpoint when I first noticed this.

[issue note font does not match style (MM).zip](https://github.com/freeplane/freeplane/files/11958498/issue.note.font.does.not.match.style.MM.zip)
![node note font does not match Note style](https://github.com/freeplane/freeplane/assets/6380301/775d23c0-189e-4155-9da7-27f8417e3582)

**Comment by kenfhill84083** [comment] 2023-07-05 16:37
This also affects the Details dialog.

**Comment by macmarrum** [comment] 2023-07-06 06:20
FYI, the attached mind map contains no images. You need to [Pack and Go-Go](https://github.com/macmarrum/freeplane-PackAndGoGo/releases) a mind map to have its images included.

In your mind map, I am also missing any **Note** or **Details** presenting the issue. And it is important because I am failing to understand the steps required to reproduce the issue.

Therefore I am guessing this is what you mean: the font-selection box in **Note** (e.g. `Edit->Note->Edit note in dialog`) shows "Sans Serif", whereas `Format->Manage Styles->Edit styles` > **Predefined styles** > **Note** > "Node font" > "Font family" is set to "Segoe UI Semilight"

And I am also guessing that the actual font (unless specifically changed for a piece of text) in **Note** is correctly set to "Segoe UI Semilight", despite the box showing "Sans Serif"

**Comment by kenfhill84083** [comment] 2023-07-06 12:47
@macmarrum, Thanks for the response.

I did not think the images were needed since the problem is text-related.  I figured the only things required were the styles.  I did not think through the attached map very well and see now how confusing it was.

After some testing, I think you are correct that the note and detail text is using the style (Segoe UI semilight 10pt) even though the dialogs report SansSerif 12pt.

That still seems like a confusing bug, though less significant.

**Comment by dpolivaev** [comment] 2023-07-16 16:32
The attached map contains no notes. I can not reproduce the issue you reported using the attached map.

**Comment by kenfhill84083** [comment] 2023-07-16 16:36
Sorry.

[New Mindmap.zip](https://github.com/freeplane/freeplane/files/12064580/New.Mindmap.zip)

**Comment by dpolivaev** [comment] 2023-07-16 16:38
Can you please check if this issue was accidentally resolved in the just published preview 1.11.5_17?

**Comment by kenfhill84083** [comment] 2023-07-16 18:18
> Can you please check if this issue was accidentally resolved in the just published preview 1.11.5_17?

No, here it is the same.  The font designated in styles is Segoe UI Semilight 10pt.  But the default font in the dialogs (notes and details) continues to SansSerif 12pt.

**Comment by dpolivaev** [comment] 2023-07-23 17:38
Preview 1.11.5_19

**Closed as completed by dpolivaev** 2023-07-23 17:38 UTC
Labels: bug

**Comment by kenfhill84083** [comment] 2023-07-23 18:17
> Preview 1.11.5_19

Working as I expect - using the fonts specified in styles.  Thanks.
