### ISSUE TITLE
Single quotes omitted if first character of node text.

### ISSUE THREAD

**Issue by ArtieGit** [freeplane/freeplane#1812] opened 2024-05-02 01:32 UTC
When a description of ['example] is entered on a node (excluding square brackets), then out of edit mode the quote does not appear.

1. Create a new node.
2. Enter a single quote as the first (or only) character as the text.
3. Click out of the node to exit editing it's description.
4. No quote appears.

The single quote should appear.

**Desktop**
 - OS: Win11 Home 23H2
 - Version 1.11.12
 - Java Version 15.0.10

**Comment by macmarrum** [comment] 2024-05-02 07:44
duplicate of
- https://github.com/freeplane/freeplane/issues/1555

**Closed as completed** 2024-06-23 11:23 UTC
Labels: duplicate, not a bug
