### ISSUE TITLE
Screen repainting issue

### ISSUE THREAD

**Issue by weeds-pests** [freeplane/freeplane#1348] opened 2023-08-18 04:31 UTC
**Describe the bug**
An image of the freeplane window is printed within the real freeplane window usually at the position of the active control.  The issue is very frequent on my machine.

**To Reproduce**
1. Can't list steps just now.  Often see this issue.  

**Expected behavior**
![2023-08-18_WindowsVersion](https://github.com/freeplane/freeplane/assets/83797807/c69aeca1-9649-4c44-a8b2-29de9314507f)

**Mind map files**
![2023-08-18_FreePlane_ScreenRepaintingIssue](https://github.com/freeplane/freeplane/assets/83797807/a3b00be2-3dc8-4715-b1cd-d4c4da60e662)

If possible, upload a zipped mind map file where the problem occurs.
[New Photos.zip](https://github.com/freeplane/freeplane/files/12375316/New.Photos.zip)

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 (see screenshot)
 - ![2023-08-18_WindowsVersion](https://github.com/freeplane/freeplane/assets/83797807/c69aeca1-9649-4c44-a8b2-29de9314507f)
 - Java Version 15.0.10

**Additional context**

**Comment by weeds-pests** [comment] 2023-08-18 04:35
freeplane version 1.11.5

**Comment by dpolivaev** [comment] 2023-08-18 08:54
I am aware of this issue reported from some multiple monitor setups where Freeplane is placed not on an upper left monitor. Unfortunately, I think that the bug is not in Freeplane itself but in Java Runtime, Windows OS, or graphic drivers, and I also do not have any setup where I could reproduce and investigate it. Therefore I am closing this issue without any solution.

As a work around you can try to place Freeplane windows on the monitor where the glitch is not appearing.

**Closed as completed by dpolivaev** 2023-08-18 08:54 UTC
Labels: bug, not reproducible, can't do

**Comment by msglog** [comment] 2023-09-08 03:30
> 
![image](https://github.com/freeplane/freeplane/assets/34530046/5b94cbde-f099-43c1-b2a3-abaaf8252f0c)

I use only one display

**Comment by euu2021** [comment] 2024-03-25 14:31
I noticed that these artifacts happen when the JScrollPane has setOpaque set to false:

![javaw_uM0NPqDpvF](https://github.com/freeplane/freeplane/assets/77707706/d12795a3-40ed-4907-9403-fab894ab5a4f)

The problem doesn't happen if it's set to true. The difference can be noted when this script has lines 122-124 set to true/false:

<details>
  <summary>script</summary>
  


```groovy
import groovy.transform.Field

import javax.swing.*
import java.awt.*
import java.awt.event.MouseAdapter
import java.awt.event.MouseEvent
import java.util.List
import javax.swing.event.ListSelectionListener

import org.freeplane.features.mode.Controller
import org.freeplane.features.map.NodeModel
import org.freeplane.features.map.INodeSelectionListener
import org.freeplane.features.nodestyle.NodeStyleController
import org.freeplane.features.styles.LogicalStyleController.StyleOption
import org.freeplane.features.ui.IMapViewChangeListener

Controller.currentController.modeController.mapController.nodeSelectionListeners.each {
    try {
        if (it.history) {
            Controller.currentController.modeController.mapController.removeNodeSelectionListener(it)
        }
    } catch(Exception ex) {
    }
}

@Field List<NodeModel> history = []
@Field List<NodeModel> pinnedItems = []

JScrollPane parentPanel
JPanel childPanel
JPanel pinnedItemsPanel

createPanels()

INodeSelectionListener mySelectionListener = new INodeSelectionListener() {
    @Override
    public void onDeselect(NodeModel node) {
        SwingUtilities.invokeLater { updateAllGUIs() }
    }

    @Override
    public void onSelect(NodeModel node) {
        if (!history.contains(node)) {
            history.add(node)
            if (history.size() > 10) {
                history.remove(0)
            }
            SwingUtilities.invokeLater { updateAllGUIs() }
        }
    }
}

createdSelectionListener = mySelectionListener

Controller.currentController.modeController.mapController.addNodeSelectionListener(mySelectionListener)

SwingUtilities.invokeLater { updateAllGUIs() }

IMapViewChangeListener myMapViewChangeListener = new IMapViewChangeListener() {
    public void afterViewChange(final Component oldView, final Component newView) {
        if (newView == null) {
            return;
        }
        createPanels()
    }
}
Controller.currentController.mapViewManager.addMapViewChangeListener(myMapViewChangeListener)

return




// ------------------ methods definitions ------------------------

def createPanels(){
    parentPanel = Controller.currentController.mapViewManager.mapView.parent.parent as JScrollPane
    Dimension parentSize = parentPanel.getSize()

    childPanel = new JPanel(new BorderLayout())
    childPanel.setBackground(new Color(0, 0, 0, 10))
    int childWidth = 80
    int childHeight = 130

    childPanel.setBounds(0, 0, childWidth, childHeight)

    parentPanel.add(childPanel)
    parentPanel.setComponentZOrder(childPanel, 0);
    parentPanel.revalidate()
    parentPanel.repaint()

    pinnedItemsPanel = new JPanel(new BorderLayout())
    pinnedItemsPanel.setBackground(new Color(0, 0, 0, 10))
    int pinnedPanelHeight = 130 // Ajuste conforme necessário
    pinnedItemsPanel.setBounds(0, childHeight + 20, childWidth, pinnedPanelHeight) // Posiciona abaixo de childPanel

    parentPanel.add(pinnedItemsPanel)
    parentPanel.setComponentZOrder(pinnedItemsPanel, 0);
    parentPanel.revalidate()
    parentPanel.repaint()
}

def updateAllGUIs() {
    updateHistoryGui()
    updatePinnedItemsGui()
}

def updateHistoryGui() {
    updateSpecifiedGUIs(history, childPanel)
}

def updatePinnedItemsGui() {
    updateSpecifiedGUIs(pinnedItems, pinnedItemsPanel)
}

def updateSpecifiedGUIs(List<NodeModel> nodes, JPanel panel) {
    panel.removeAll()

    DefaultListModel<NodeModel> listModel = new DefaultListModel<>()
    nodes.each { listModel.addElement(it) }
    JList<NodeModel> jList = new JList<>(listModel)

    JScrollPane scrollPane = new JScrollPane(jList)
    jList.setOpaque(false)
    scrollPane.setOpaque(false)
    scrollPane.getViewport().setOpaque(false)

    scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER)
    scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER)

    jList.setCellRenderer(new DefaultListCellRenderer() {
        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus)
            NodeModel nodeItem = (NodeModel) value

            Color nodeBackgroundColor = NodeStyleController.getController().getBackgroundColor(nodeItem, StyleOption.FOR_UNSELECTED_NODE)
            Color nodeFontColor = NodeStyleController.getController().getColor(nodeItem, StyleOption.FOR_UNSELECTED_NODE)

            if (isSelected) {
                label.setBackground(list.getSelectionBackground())
                label.setForeground(list.getSelectionForeground())
            } else {
                label.setBackground(nodeBackgroundColor)
                label.setForeground(nodeFontColor)
            }
            if (pinnedItems.contains(nodeItem)){
                label.setText("📌" + label.getText())}
            currentMapView = Controller.currentController.MapViewManager.mapView
            if (currentMapView.currentRootParentView == null) {return label}
            if (nodeItem.getPathToRoot().find{it == currentMapView.mapSelection.selectionRoot}){return label}
            label.setText("☠️|" + label.getText())
            return label
        }
    })

    jList.addListSelectionListener({ e ->
        if (!e.getValueIsAdjusting()) {
            Integer selectedItemIndex = jList.getSelectedIndex()
            NodeModel selectedItemNode = nodes[selectedItemIndex]
            Controller.currentController.mapViewManager.mapView.getMapSelection().selectAsTheOnlyOneSelected(selectedItemNode)
        }
    } as ListSelectionListener)

    jList.addMouseListener(new MouseAdapter() {
        @Override
        void mousePressed(MouseEvent e) {
            if (SwingUtilities.isRightMouseButton(e)) {
                int index = jList.locationToIndex(e.getPoint())
                if (index >= 0) {
                    jList.setSelectedIndex(index)
                    JPopupMenu popupMenu = new JPopupMenu()
                    JMenuItem pinItem = new JMenuItem("Fixar Item")
                    pinItem.addActionListener({
                        pinnedItems.add(nodes[index])
                        updatePinnedItemsGui() // Atualizar a GUI para os itens fixados
                    })
                    popupMenu.add(pinItem)
                    popupMenu.show(e.getComponent(), e.getX(), e.getY())
                }
            }
        }
    })

    panel.add(scrollPane, BorderLayout.CENTER)
    panel.revalidate()
    panel.repaint()
}
```

</details>

**Comment by dpolivaev** [comment] 2024-03-25 17:55
@euu2021 
IMHO false opaque flag is the default for JScrollPane.
Can you add line setOpaque(true) to org.freeplane.view.swing.map.MapViewScrollPane.MapViewScrollPane() and check if it resolves the issue?

**Comment by euu2021** [comment] 2024-03-25 21:41
> @euu2021 IMHO false opaque flag is the default for JScrollPane. Can you add line setOpaque(true) to org.freeplane.view.swing.map.MapViewScrollPane.MapViewScrollPane() and check if it resolves the issue?

Some things that I noticed:

In my script, I only get the artifacts if all the three elements are setOpaque(false):

```
    jList.setOpaque(false)
    scrollPane.setOpaque(false)
    scrollPane.getViewport().setOpaque(false)
```

The default flag for the new map views is setOpaque(true) for both elements, in some of the themes:


![image](https://github.com/freeplane/freeplane/assets/77707706/86a41b67-72bb-475b-bdc4-73ce4653e513)


  




But, in the Darcula theme:

  

![image](https://github.com/freeplane/freeplane/assets/77707706/33413441-4fbb-4272-bba5-13d5b6540e74)


And the documentation explains:

![image](https://github.com/freeplane/freeplane/assets/77707706/68e4d404-a42d-4149-a395-5c2be379434c)


So, if my calculation is correct, if OP changes to Darcula, the problem will stop happening. I cannot test, because I don't see those artifacts in the FP window, only at the frames created by me.

Another interest test is to use this script to change the setOpaque() of the current map view elements:

```
import javax.swing.JScrollPane
import org.freeplane.features.mode.Controller
import org.freeplane.view.swing.map.MapView

MapView mapView = Controller.currentController.mapViewManager.mapView

JScrollPane findScrollPaneParent(java.awt.Component component) {
    while (component != null && !(component instanceof JScrollPane)) {
        component = component.getParent()
    }
    return component as JScrollPane
}

JScrollPane mapViewScrollPane = findScrollPaneParent(mapView)

mapViewScrollPane.opaque = true
mapViewScrollPane.viewport.opaque = true
```

**Comment by euu2021** [comment] 2024-03-26 00:37
actually, I noticed that the panels that I create always have the artifacts. What happens is that it is covered by the panels. I noticed that because some of the Look And Feels shrink a bit the child panel, making the parent JPanel show up a bit. 

Here, I've made the three child components (JScrollPane, Viewport, JList) opaque, and then the parent panel (JPanel) semitransparent. The second panel in the image have a green semitransparent JPanel, so you can see parts of it:
![image](https://github.com/freeplane/freeplane/assets/77707706/3cdd7236-5eb7-42ef-b3c3-00af5051b402)

The first JPanel is transparent, and you can see the artifacts happening behind it (and also behind the second one, as it is semitransparent):

![javaw_uwVKS0IXeR](https://github.com/freeplane/freeplane/assets/77707706/e29835bb-61f7-454c-9c9a-1b62efe0cf39)



<details>
  <summary>This is the script that I used:</summary>
  
  



```groovy
import groovy.transform.Field

import javax.swing.*
import java.awt.*
import java.awt.event.MouseAdapter
import java.awt.event.MouseEvent
import java.util.List
import javax.swing.event.ListSelectionListener

import org.freeplane.features.mode.Controller
import org.freeplane.features.map.NodeModel
import org.freeplane.features.map.INodeSelectionListener
import org.freeplane.features.nodestyle.NodeStyleController
import org.freeplane.features.styles.LogicalStyleController.StyleOption
import org.freeplane.features.ui.IMapViewChangeListener

Controller.currentController.modeController.mapController.nodeSelectionListeners.each {
    try {
        if (it.history) {
            Controller.currentController.modeController.mapController.removeNodeSelectionListener(it)
        }
    } catch(Exception ex) {
    }
}

@Field List<NodeModel> history = []
@Field List<NodeModel> pinnedItems = []

JScrollPane parentPanel
JPanel childPanel
JPanel pinnedItemsPanel

createPanels()

INodeSelectionListener mySelectionListener = new INodeSelectionListener() {
    @Override
    public void onDeselect(NodeModel node) {
        SwingUtilities.invokeLater { updateAllGUIs() }
    }

    @Override
    public void onSelect(NodeModel node) {
        if (!history.contains(node)) {
            history.add(node)
            if (history.size() > 10) {
                history.remove(0)
            }
            SwingUtilities.invokeLater { updateAllGUIs() }
        }
    }
}

createdSelectionListener = mySelectionListener

Controller.currentController.modeController.mapController.addNodeSelectionListener(mySelectionListener)

SwingUtilities.invokeLater { updateAllGUIs() }

IMapViewChangeListener myMapViewChangeListener = new IMapViewChangeListener() {
    public void afterViewChange(final Component oldView, final Component newView) {
        if (newView == null) {
            return;
        }
        createPanels()
    }
}
Controller.currentController.mapViewManager.addMapViewChangeListener(myMapViewChangeListener)

return




// ------------------ methods definitions ------------------------

def createPanels(){
    parentPanel = Controller.currentController.mapViewManager.mapView.parent.parent as JScrollPane
    Dimension parentSize = parentPanel.getSize()

    childPanel = new JPanel(new BorderLayout())
    childPanel.setBackground(new Color(0, 0, 0, 10))
    int childWidth = 80
    int childHeight = 130

    childPanel.setBounds(0, 0, childWidth, childHeight)

    parentPanel.add(childPanel)
    parentPanel.setComponentZOrder(childPanel, 0);
    parentPanel.revalidate()
    parentPanel.repaint()

    pinnedItemsPanel = new JPanel(new BorderLayout())
    pinnedItemsPanel.setBackground(new Color(0, 200, 0, 130))
    int pinnedPanelHeight = 130 // Ajuste conforme necessário
    pinnedItemsPanel.setBounds(0, childHeight + 20, childWidth, pinnedPanelHeight) // Posiciona abaixo de childPanel

    parentPanel.add(pinnedItemsPanel)
    parentPanel.setComponentZOrder(pinnedItemsPanel, 0);
    parentPanel.revalidate()
    parentPanel.repaint()
}

def updateAllGUIs() {
    updateHistoryGui()
    updatePinnedItemsGui()
}

def updateHistoryGui() {
    updateSpecifiedGUIs(history, childPanel)
}

def updatePinnedItemsGui() {
    updateSpecifiedGUIs(pinnedItems, pinnedItemsPanel)
}

def updateSpecifiedGUIs(List<NodeModel> nodes, JPanel panel) {
    panel.removeAll()

    DefaultListModel<NodeModel> listModel = new DefaultListModel<>()
    nodes.each { listModel.addElement(it) }
    JList<NodeModel> jList = new JList<>(listModel)

    JScrollPane scrollPane = new JScrollPane(jList)
    jList.setOpaque(true)
    scrollPane.setOpaque(true)
    scrollPane.getViewport().setOpaque(true)

    scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER)
    scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER)

    jList.setCellRenderer(new DefaultListCellRenderer() {
        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus)
            NodeModel nodeItem = (NodeModel) value

            Color nodeBackgroundColor = NodeStyleController.getController().getBackgroundColor(nodeItem, StyleOption.FOR_UNSELECTED_NODE)
            Color nodeFontColor = NodeStyleController.getController().getColor(nodeItem, StyleOption.FOR_UNSELECTED_NODE)

            if (isSelected) {
                label.setBackground(list.getSelectionBackground())
                label.setForeground(list.getSelectionForeground())
            } else {
                label.setBackground(nodeBackgroundColor)
                label.setForeground(nodeFontColor)
            }
            if (pinnedItems.contains(nodeItem)){
                label.setText("📌" + label.getText())}
            currentMapView = Controller.currentController.MapViewManager.mapView
            if (currentMapView.currentRootParentView == null) {return label}
            if (nodeItem.getPathToRoot().find{it == currentMapView.mapSelection.selectionRoot}){return label}
            label.setText("☠️|" + label.getText())
            return label
        }
    })

    jList.addListSelectionListener({ e ->
        if (!e.getValueIsAdjusting()) {
            Integer selectedItemIndex = jList.getSelectedIndex()
            NodeModel selectedItemNode = nodes[selectedItemIndex]
            Controller.currentController.mapViewManager.mapView.getMapSelection().selectAsTheOnlyOneSelected(selectedItemNode)
        }
    } as ListSelectionListener)

    jList.addMouseListener(new MouseAdapter() {
        @Override
        void mousePressed(MouseEvent e) {
            if (SwingUtilities.isRightMouseButton(e)) {
                int index = jList.locationToIndex(e.getPoint())
                if (index >= 0) {
                    jList.setSelectedIndex(index)
                    JPopupMenu popupMenu = new JPopupMenu()
                    JMenuItem pinItem = new JMenuItem("Fixar Item")
                    pinItem.addActionListener({
                        pinnedItems.add(nodes[index])
                        updatePinnedItemsGui() // Atualizar a GUI para os itens fixados
                    })
                    popupMenu.add(pinItem)
                    popupMenu.show(e.getComponent(), e.getX(), e.getY())
                }
            }
        }
    })

    panel.add(scrollPane, BorderLayout.CENTER)
    panel.revalidate()
    panel.revalidate()
    panel.repaint()
}
```

</details>

Tomorrow, I will make more controlled tests, aiming for specific kinds of panels, trying to isolate the problem.

For clarification: I never noticed artifacts in the FreePlane window. I only see them when I create the panels.

**Comment by euu2021** [comment] 2024-03-27 10:57
[This page](https://tips4java.wordpress.com/2009/05/31/backgrounds-with-transparency/) explains that the Swing components have a problem with transparency. I applied the solution pointed in the page, and it worked. Now, I can make transparent panels, with no problems.

I don't know how it relates to the OP problem, though.
