### ISSUE TITLE
Error messages at startup, when invalid Desktop links exist

### ISSUE THREAD

**Issue by geogiraux** [freeplane/freeplane#131] opened 2019-04-07 13:48 UTC
Hello
I'm having the same issue as this one described [here](https://sourceforge.net/p/freeplane/discussion/758437/thread/b6a22835f4/). Using freeplane 1.7.7 from freeplane-bin.zip file and jre 1.8.60
I guess freeplane is trying to build or preload a file tree of some kind of defaults folders when you run freeplane in file browser mode. Not a big deal, but I can't remove the invalid shortcut since it's a share I use one another network
thanks

**Comment by dpolivaev** [comment] 2019-04-07 16:45
Unfortunately I do not know the cause of this problem. Freeplane code does not intentionally access any files not related to freeplane distribution, configuration or the mind maps.

If you have any ideas please share.

**Comment by dpolivaev** [comment] 2019-04-13 11:24
Good news: there is a Java bug introduced in Java 8 Update 191. It is reported to be fixed in Java 8 Update 211 and Java 11.0.3. The versions should be released on April 16, 2019.

Please check it out.

https://bugs.openjdk.java.net/browse/JDK-8213583
https://blogs.oracle.com/java-platform-group/oracle-java-se-releases-faq

**Closed as completed by dpolivaev** 2019-04-13 11:24 UTC

**Comment by ldmpub** [comment] 2019-04-17 14:00
Thanks for these info.

I can confirm: pb fixed after updating Java to 1.8.0_201

**Comment by geogiraux** [comment] 2019-04-23 09:14
Thanks, I can confirm pb is fixed too
