### ISSUE TITLE
 Center selected node at left) doesn't work

### ISSUE THREAD

**Issue by dpolivaev** [freeplane/freeplane#1158] opened 2023-05-20 17:19 UTC
Thanks for trying to fix this issue, but Unfortunately the bug wasn't fully fixed and another bug appeared:
the map view will follow the selection for the first time (when you select the first node and press (Shift+Page Down),
but when I repeat the process from the last node upward using (Shift+Page Up): it doesn't work again.
and here is a new bug appears: the option to scroll the map from the menu fails 
 (View > Scroll map > Center selected node at left) doesn't work

You can see all the details in this video:

https://github.com/freeplane/freeplane/assets/129968602/2c6b4f93-5846-4870-bc75-ee7678c68941

_Originally posted by @Bricklam in https://github.com/freeplane/freeplane/issues/1141#issuecomment-1555955115_

**Comment by Bricklam** [comment] 2023-05-20 18:36
Sorry, forgot to attach this bug report, it might help
 (appears when I try to repeat the previous process) (selecting nodes by shift+page up/down)

=========================================================================
STDOUT: May 20, 2023 6:37:29 PM org.freeplane.core.util.LogUtils info
INFO: freeplane_version = 1.11.3; freeplane_xml_version = freeplane 1.11.1
git revision = a0b190b6ea95c5dc126bc64e8a770e70bbe1a1f1 dpolivaev 2023-05-19T15:36:34Z
java_version = 17.0.6; os_name = Windows 10; os_version = 10.0
STDOUT: May 20, 2023 6:37:30 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date format M/d/yy
STDOUT: May 20, 2023 6:37:30 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date time format M/d/yy, h:mm a
STDOUT: Framework launched
STDOUT: May 20, 2023 6:37:35 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://3:1/org/freeplane/plugin/formula/defaults.properties
STDOUT: May 20, 2023 6:37:35 PM org.freeplane.core.util.LogUtils info
INFO: extending script's classpath by [E:\TEMP\FP_1.11.3-pre01_Launcher\FreeplanePortable\Data\Freeplane\1.11.x\compiledscripts, E:\TEMP\FP_1.11.3-pre01_Launcher\FreeplanePortable\Data\Freeplane\1.11.x\lib]
STDOUT: May 20, 2023 6:37:35 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://8:1/org/freeplane/plugin/script/defaults.properties
STDOUT: May 20, 2023 6:37:35 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: May 20, 2023 6:37:35 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: May 20, 2023 6:37:39 PM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
STDOUT: May 20, 2023 6:37:42 PM org.freeplane.core.util.LogUtils info
INFO: menu items to execute: []
STDERR: May 20, 2023 7:29:50 PM org.freeplane.core.util.LogUtils severe
SEVERE: Can not select next visible sibling in continious selection, endless loop
STDOUT: May 20, 2023 7:29:53 PM org.freeplane.core.util.LogUtils info
INFO: execute [rundll32, url.dll,FileProtocolHandler, file:/E:/TEMP/FP_1.11.3-pre01_Launcher/FreeplanePortable/Data/Freeplane/1.11.x/logs/]

**Comment by Bricklam** [comment] 2023-05-21 04:29
Sorry, I also found another bug in the map view in (1.11.3_pre01):
(it appears to be related to the previous bug, or maybe it is the same bug triggered by different action),
the details are in the video:

https://github.com/freeplane/freeplane/assets/129968602/b6bfaf37-da79-4825-921d-23b94f20bb5f

**Comment by dpolivaev** [comment] 2023-05-21 10:59
I can not reproduce the issue about "Center selected node at left". I could fix all other issues. 
After I release the fixes please check if you still this bug and attach your example mind map and your auto.properties.

I generally always appreciate attached example maps and attached auto.properties because if I have only videos, I am not always able to reproduce the reports and I always loose too much time trying.

**Comment by Bricklam** [comment] 2023-05-21 16:46
I have checked the new version (1.11.3_pre02) and all the bugs in (1.11.3_pre01) are FIXED successfully.
thanks for your work

I'm sorry that you couldn't reproduce the "Center selected node at left" bug in (1.11.3_pre01), I did more research,
and found out that maybe using the mouse to move the map will cause the bug to disappear.
or my previous actions in the previous video weren't certainly able to produce the bug.

Anyway, if you are still interested in reproducing the bug in the previous version (1.11.3_pre01):
I have found out other actions that certainly re-produce the same bug, and made a new video showing these actions in details.
(if followed carefully: you should be able to re-produce the same bug in the version (1.11.3_pre01)),
I have also attached the required files: (the map file, auto.properties), 

but be careful, to be able to re-produce the bug successfully:
avoid using the mouse/touchpad to move/drag the map canvas, (like you see in the new video,)
(I used the mouse only to select the first node, then at the end to apply the option: (center selected node at left)
I mostly used the keyboard shortcut (Shift+Page Up) and (Shift+Page Down) consecutively, as displayed in the new video

here is the map file, auto.properties file:
[test.zip](https://github.com/freeplane/freeplane/files/11525051/test.zip)


and here is the new video: (with all the key presses displayed in the left side)

https://github.com/freeplane/freeplane/assets/129968602/f96aab51-1291-4fca-a769-8292bf27b25b

**Comment by dpolivaev** [comment] 2023-05-21 16:55
If this bug is fixed with my latest changes, it is fine, and I do not need to reproduce it any longer.
Is it fixed in 1.11.3_02?

**Comment by Bricklam** [comment] 2023-05-21 18:36
Yes. it is fixed in (1.11.3_02), all the bugs are gone.  you can close this issue
thank you very much

**Comment by dpolivaev** [comment] 2023-05-21 18:39
Thank you

**Closed as completed** 2023-05-21 18:39 UTC
Labels: bug
